example:
  property: I AM DEV

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/ostock_dev
    username: postgres
    password: postgres
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: true


#example.property= I AM DEV
#
## DataSource settings: set here your own configurations for the database
#spring.datasource.url = jdbc:postgresql://database:5432/ostock_dev?sslmode=disable
#spring.datasource.username = postgres
#spring.datasource.password = {cipher}f4609209a3e75d8ac79a5e3063ce151c2cd28aa431170bb06974b9421e807b6a
#
#security.oauth2.resource.userInfoUri= http://authenticationservice:8082/user